### ISSUE TITLE
Clicking the thumbnail of the photos should...:

### ISSUE THREAD

**Issue by Bruniz** [WatchDoges/WatchDoge#61]

**Comment by ghost** [comment]
1: Display a small pop-up with all currently taken pictures, so that the user can select any of them.
2: Selecting them opens it in full screen and the user can delete it if he/she wants.
3: The user can also navigate the rest of the photos/videos by swiping left/right in this full screen view.
4: The user should be able to return to the MainActivity when he/she is done looking at / deleting Files.

**Comment by ghost** [comment]
Note: Gallery object is apparently deprecatied. Should not be used to implement this!
